name: Minecraft Server
description: minecraft server with itzg/minecraft-server
slug: minecraft_server
homeassistant_api: true
version: "3.1.0"
arch:
  - aarch64
  - amd64
startup: services
ports:
  25565/tcp: 25565
  24454/udp: 24454
environment:
  EULA: "TRUE"
  DIFFICULTY: "2"
  MAX_PLAYERS: "10"
  MOTD: "Stierzunge"
  INIT_MEMORY: "1G"
  MAX_MEMORY: "4G"
  ENABLE_AUTOPAUSE: "TRUE"
  AUTOPAUSE_TIMEOUT_EST: "600"
  AUTOPAUSE_TIMEOUT_INIT: "600"
  SERVER_PORT: "25565"
  VIEW_DISTANCE: "12"
  SIMULATION_DISTANCE: "8"
  TYPE: "PAPER"
