name: Minecraft Server
description: minecraft server with itzg/minecraft-server
slug: minecraft_server
homeassistant_api: true
version: "2.0.3"
arch:
  - aarch64
  - amd64
startup: services
ports:
  25565/tcp: 25565
environment:
  EULA: "TRUE"
  DIFFICULTY: "2"
  MAX_PLAYERS: "10"
  MOTD: "Stierzunge"
  MEMORY: "6G"
  SERVER_PORT: "25565"
  VIEW_DISTANCE: "16"
  TYPE: "PAPER"
map:
  - type: share
    read_only: false
    path: /data
